from tests.support.utils import format_to_bytes

GYD_TOKEN_ADDRESS = format_to_bytes("GYD_TOKEN_ADDRESS", 32)
PAMM_ADDRESS = format_to_bytes("PAMM_ADDRESS", 32)
RESERVE_ADDRESS = format_to_bytes("RESERVE_ADDRESS", 32)
ROOT_PRICE_ORACLE_ADDRESS = format_to_bytes("ROOT_PRICE_ORACLE_ADDRESS", 32)
ROOT_SAFETY_CHECK_ADDRESS = format_to_bytes("ROOT_SAFETY_CHECK_ADDRESS", 32)
VAULT_REGISTRY_ADDRESS = format_to_bytes("VAULT_REGISTRY_ADDRESS", 32)
ASSET_REGISTRY_ADDRESS = format_to_bytes("ASSET_REGISTRY_ADDRESS", 32)
RESERVE_MANAGER_ADDRESS = format_to_bytes("RESERVE_MANAGER_ADDRESS", 32)
FEE_HANDLER_ADDRESS = format_to_bytes("FEE_HANDLER_ADDRESS", 32)
MOTHERBOARD_ADDRESS = format_to_bytes("MOTHERBOARD_ADDRESS", 32)
GYD_RECOVERY_ADDRESS = format_to_bytes("GYD_RECOVERY_ADDRESS", 32)
BALANCER_VAULT_ADDRESS = format_to_bytes("BALANCER_VAULT_ADDRESS", 32)
GOV_TREASURY_ADDRESS = format_to_bytes("GOV_TREASURY_ADDRESS", 32)


GYD_RECOVERY_TRIGGER_CR = format_to_bytes("GYD_RECOVERY_TRIGGER_CR", 32)
GYD_RECOVERY_TARGET_CR = format_to_bytes("GYD_RECOVERY_TARGET_CR", 32)

STEWARDSHIP_INC_ADDRESS = format_to_bytes("STEWARDSHIP_INC_ADDRESS", 32)
STEWARDSHIP_INC_MIN_CR = format_to_bytes("STEWARDSHIP_INC_MIN_CR", 32)
STEWARDSHIP_INC_DURATION = format_to_bytes("STEWARDSHIP_INC_DURATION", 32)
STEWARDSHIP_INC_MAX_VIOLATIONS = format_to_bytes("STEWARDSHIP_INC_MAX_VIOLATIONS", 32)

SAFETY_BLOCKS_AUTOMATIC = format_to_bytes("SAFETY_BLOCKS_AUTOMATIC", 32)
SAFETY_BLOCKS_GUARDIAN = format_to_bytes("SAFETY_BLOCKS_GUARDIAN", 32)

REDEEM_DISCOUNT_RATIO = format_to_bytes("REDEEM_DISCOUNT_RATIO", 32)
VAULT_DUST_THRESHOLD = format_to_bytes("VAULT_DUST_THRESHOLD", 32)
STABLECOIN_MAX_DEVIATION = format_to_bytes("STABLECOIN_MAX_DEVIATION", 32)

PROTOCOL_SWAP_FEE_PERC = format_to_bytes("PROTOCOL_SWAP_FEE_PERC", 32)
PROTOCOL_FEE_GYRO_PORTION = format_to_bytes("PROTOCOL_FEE_GYRO_PORTION", 32)
GYRO_TREASURY = format_to_bytes("GYRO_TREASURY", 32)
BAL_TREASURY = format_to_bytes("BAL_TREASURY", 32)
