from tests.support.utils import format_to_bytes

GYD_TOKEN_ADDRESS = format_to_bytes("GYD_TOKEN_ADDRESS", 32)
EXCHANGER_REGISTRY_ADDRESS = format_to_bytes("EXCHANGER_REGISTRY_ADDRESS", 32)
PAMM_ADDRESS = format_to_bytes("PAMM_ADDRESS", 32)
FEE_BANK_ADDRESS = format_to_bytes("FEE_BANK_ADDRESS", 32)
RESERVE_ADDRESS = format_to_bytes("RESERVE_ADDRESS", 32)
ASSET_PRICER_ADDRESS = format_to_bytes("ASSET_PRICER_ADDRESS", 32)
ROOT_PRICE_ORACLE_ADDRESS = format_to_bytes("ROOT_PRICE_ORACLE_ADDRESS", 32)
ROOT_SAFETY_CHECK_ADDRESS = format_to_bytes("ROOT_SAFETY_CHECK_ADDRESS", 32)
VAULT_REGISTRY_ADDRESS = format_to_bytes("VAULT_REGISTRY_ADDRESS", 32)
VAULT_MANAGER_ADDRESS = format_to_bytes("VAULT_MANAGER_ADDRESS", 32)
MINT_FEE = format_to_bytes("MINT_FEE", 32)
