from tests.support.utils import format_to_bytes

GYD_TOKEN_ADDRESS = format_to_bytes("GYD_TOKEN_ADDRESS", 32)
PAMM_ADDRESS = format_to_bytes("PAMM_ADDRESS", 32)
FEE_BANK_ADDRESS = format_to_bytes("FEE_BANK_ADDRESS", 32)
RESERVE_ADDRESS = format_to_bytes("RESERVE_ADDRESS", 32)
ROOT_PRICE_ORACLE_ADDRESS = format_to_bytes("ROOT_PRICE_ORACLE_ADDRESS", 32)
ROOT_SAFETY_CHECK_ADDRESS = format_to_bytes("ROOT_SAFETY_CHECK_ADDRESS", 32)
VAULT_REGISTRY_ADDRESS = format_to_bytes("VAULT_REGISTRY_ADDRESS", 32)
ASSET_REGISTRY_ADDRESS = format_to_bytes("ASSET_REGISTRY_ADDRESS", 32)
RESERVE_MANAGER_ADDRESS = format_to_bytes("RESERVE_MANAGER_ADDRESS", 32)
FEE_HANDLER_ADDRESS = format_to_bytes("FEE_HANDLER_ADDRESS", 32)
MOTHERBOARD_ADDRESS = format_to_bytes("MOTHERBOARD_ADDRESS", 32)
CAP_AUTHENTICATION_ADDRESS = format_to_bytes("CAP_AUTHENTICATION_ADDRESS", 32)
BALANCER_VAULT_ADDRESS = format_to_bytes("BALANCER_VAULT_ADDRESS", 32)


GYD_GLOBAL_SUPPLY_CAP = format_to_bytes("GYD_GLOBAL_SUPPLY_CAP", 32)
GYD_AUTHENTICATED_USER_CAP = format_to_bytes("GYD_AUTHENTICATED_USER_CAP", 32)
GYD_USER_CAP = format_to_bytes("GYD_USER_CAP", 32)

STEWARDSHIP_INC_ADDRESS = format_to_bytes("STEWARDSHIP_INC_ADDRESS", 32)
STEWARDSHIP_INC_MIN_CR = format_to_bytes("STEWARDSHIP_INC_MIN_CR", 32)
STEWARDSHIP_INC_DURATION = format_to_bytes("STEWARDSHIP_INC_DURATION", 32)
STEWARDSHIP_INC_MAX_VIOLATIONS = format_to_bytes("STEWARDSHIP_INC_MAX_VIOLATIONS", 32)
