from http.client import INSUFFICIENT_STORAGE


TOKEN_AND_AMOUNTS_LENGTH_DIFFER = "1"
TOO_MUCH_SLIPPAGE = "2"
EXCHANGER_NOT_FOUND = "3"
POOL_IDS_NOT_FOUND = "4"
WOULD_UNBALANCE_GYROSCOPE = "5"
VAULT_ALREADY_EXISTS = "6"
VAULT_NOT_FOUND = "7"

X_OUT_OF_BOUNDS = "20"
Y_OUT_OF_BOUNDS = "21"
PRODUCT_OUT_OF_BOUNDS = "22"
INVALID_EXPONENT = "23"
OUT_OF_BOUNDS = "24"
ZERO_DIVISION = "25"

NOT_AUTHORIZED = "30"
INVALID_ARGUMENT = "31"
KEY_NOT_FOUND = "32"
KEY_FROZEN = "33"
INSUFFICIENT_BALANCE = "34"

ASSET_NOT_SUPPORTED = "40"
STALE_PRICE = "41"
NEGATIVE_PRICE = "42"
INVALID_MESSAGE = "43"
TOO_MUCH_VOLATILITY = "44"

POOL_HAS_ZERO_USD_VALUE = "51"
POOL_DOES_NOT_HAVE_LIVENESS = "52"
POOL_IS_PAUSED = "53"
ASSETS_NOT_CLOSE_TO_POOL_WEIGHTS = "54"
STABLECOIN_IN_POOL_NOT_CLOSE_TO_PEG = "55"
DIFFERENT_NUMBER_OF_TOKENS_TO_BALANCES = "56"
POOL_DOES_NOT_HAVE_NORMALIZED_WEIGHTS_SET = "57"
NO_POOL_ID_REGISTERED = "58"
