from http.client import INSUFFICIENT_STORAGE


TOKEN_AND_AMOUNTS_LENGTH_DIFFER = "1"
TOO_MUCH_SLIPPAGE = "2"
EXCHANGER_NOT_FOUND = "3"
POOL_IDS_NOT_FOUND = "4"
WOULD_UNBALANCE_GYROSCOPE = "5"
VAULT_ALREADY_EXISTS = "6"
VAULT_NOT_FOUND = "7"

X_OUT_OF_BOUNDS = "20"
Y_OUT_OF_BOUNDS = "21"
PRODUCT_OUT_OF_BOUNDS = "22"
INVALID_EXPONENT = "23"
OUT_OF_BOUNDS = "24"
ZERO_DIVISION = "25"
ADD_OVERFLOW = "26"
SUB_OVERFLOW = "27"
MUL_OVERFLOW = "28"
DIV_INTERNAL = "29"


NOT_AUTHORIZED = "30"
INVALID_ARGUMENT = "31"
KEY_NOT_FOUND = "32"
KEY_FROZEN = "33"
INSUFFICIENT_BALANCE = "34"

ASSET_NOT_SUPPORTED = "40"
STALE_PRICE = "41"
NEGATIVE_PRICE = "42"
INVALID_MESSAGE = "43"
TOO_MUCH_VOLATILITY = "44"
TOO_MUCH_VOLATILITY = "44"
WETH_ADDRESS_NOT_FIRST = "44"
ROOT_PRICE_NOT_GROUNDED = "45"
NOT_ENOUGH_TWAPS = "46"
ZERO_PRICE_TWAP = "47"
INVALID_NUMBER_WEIGHTS = "48"
NO_WETH_PRICE = "49"


A_VAULT_HAS_ALL_STABLECOINS_OFF_PEG = "51"
NOT_SAFE_TO_MINT = "52"
NOT_SAFE_TO_REDEEM = "53"
AMOUNT_AND_PRICE_LENGTH_DIFFER = "54"
TOKEN_PRICES_TOO_SMALL = "55"
TRYING_TO_REDEEM_MORE_THAN_VAULT_CONTAINS = "56"
CALLER_NOT_MOTHERBOARD = "57"
CALLER_NOT_RESERVE_MANAGER = "58"
VAULT_CANNOT_BE_REMOVED = "59"

NO_POOL_ID_REGISTERED = "58"

VAULT_FLOW_TOO_HIGH = "60"
OPERATION_SUCCEEDS_BUT_SAFETY_MODE_ACTIVATED = "61"
SUPPLY_CAP_EXCEEDED = "64"
SAFETY_MODE_ACTIVATED = "65"

REDEEM_AMOUNT_BUG = "100"
TOKENS_NOT_SORTED = "102"

TRYING_TO_REDEEM_MORE_THAN_SUPPLY = "104"

